/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package room.booking.system;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ZacharyAZY
 */
public class newBookingForm extends javax.swing.JFrame {

    private String bookingId;
    private String roomId;
    private LocalDate startDate;
    private LocalDate endDate;
    private long daysOfStay;
    private static final double ROOM_PRICE_PER_NIGHT = 350.00;
    private static final String EMAIL_REGEX = "^(.+)@(.+)$";

    public newBookingForm(String bookingId, String roomId, LocalDate startDate, LocalDate endDate) {
        this.bookingId = bookingId;
        this.roomId = roomId;
        this.startDate = startDate;
        this.endDate = endDate;
        this.daysOfStay = ChronoUnit.DAYS.between(startDate, endDate) + 1;
        initComponents();
        bookingIdField.setText(bookingId);
        roomIdField.setText(roomId);
        startDateField.setText(String.valueOf(startDate));
        daysOfStayField.setText(String.valueOf(daysOfStay));
    }

    //Gradient JPanel
    class jPanelGradient extends JPanel {

        @Override
        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();

            Color color1 = new Color(127, 154, 227);
            Color color2 = new Color(227, 127, 202);
            GradientPaint gp = new GradientPaint(0, 180, color1, 180, 0, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        receiptPanel = new javax.swing.JPanel();
        receiptBookingIdLabel = new javax.swing.JLabel();
        receiptBookingId = new javax.swing.JLabel();
        receiptRoomIdLabel = new javax.swing.JLabel();
        receiptRoomId = new javax.swing.JLabel();
        receiptStartDateLabel = new javax.swing.JLabel();
        receiptStartDate = new javax.swing.JLabel();
        receiptDaysOfStayLabel = new javax.swing.JLabel();
        receiptDaysOfStay = new javax.swing.JLabel();
        receiptCustNameLabel = new javax.swing.JLabel();
        receiptCustName = new javax.swing.JLabel();
        receiptServiceTaxLabel = new javax.swing.JLabel();
        receiptServiceTax = new javax.swing.JLabel();
        receiptTourismTaxLabel = new javax.swing.JLabel();
        receiptTourismTax = new javax.swing.JLabel();
        receiptTotalPriceLabel = new javax.swing.JLabel();
        receiptTotalPrice = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new jPanelGradient();
        bookingFormLabel = new javax.swing.JLabel();
        bookingIdLabel = new javax.swing.JLabel();
        bookingIdField = new javax.swing.JTextField();
        roomIdLabel = new javax.swing.JLabel();
        roomIdField = new javax.swing.JTextField();
        daysofStayLabel = new javax.swing.JLabel();
        daysOfStayField = new javax.swing.JTextField();
        crtCustNameLabel = new javax.swing.JLabel();
        crtCustNameField = new javax.swing.JTextField();
        crtICNumLabel = new javax.swing.JLabel();
        crtICNumField = new javax.swing.JTextField();
        crtTelNoLabel = new javax.swing.JLabel();
        crtTelNoField = new javax.swing.JFormattedTextField();
        crtEmailLabel = new javax.swing.JLabel();
        crtEmailField = new javax.swing.JTextField();
        startDateLabel = new javax.swing.JLabel();
        startDateField = new javax.swing.JTextField();
        crtBookingBtn = new javax.swing.JButton();
        cancelBookingBtn = new javax.swing.JButton();

        receiptBookingIdLabel.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        receiptBookingIdLabel.setForeground(new java.awt.Color(0, 0, 0));
        receiptBookingIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        receiptBookingIdLabel.setText("Booking ID:");

        receiptBookingId.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        receiptBookingId.setForeground(new java.awt.Color(0, 0, 0));
        receiptBookingId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        receiptRoomIdLabel.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        receiptRoomIdLabel.setForeground(new java.awt.Color(0, 0, 0));
        receiptRoomIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        receiptRoomIdLabel.setText("Room ID:");

        receiptRoomId.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        receiptRoomId.setForeground(new java.awt.Color(0, 0, 0));
        receiptRoomId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        receiptStartDateLabel.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        receiptStartDateLabel.setForeground(new java.awt.Color(0, 0, 0));
        receiptStartDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        receiptStartDateLabel.setText("Start Date:");

        receiptStartDate.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        receiptStartDate.setForeground(new java.awt.Color(0, 0, 0));
        receiptStartDate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        receiptDaysOfStayLabel.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        receiptDaysOfStayLabel.setForeground(new java.awt.Color(0, 0, 0));
        receiptDaysOfStayLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        receiptDaysOfStayLabel.setText("Days Of Stay:");

        receiptDaysOfStay.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        receiptDaysOfStay.setForeground(new java.awt.Color(0, 0, 0));
        receiptDaysOfStay.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        receiptCustNameLabel.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        receiptCustNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        receiptCustNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        receiptCustNameLabel.setText("Customer Name:");

        receiptCustName.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        receiptCustName.setForeground(new java.awt.Color(0, 0, 0));
        receiptCustName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        receiptServiceTaxLabel.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        receiptServiceTaxLabel.setForeground(new java.awt.Color(0, 153, 102));
        receiptServiceTaxLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        receiptServiceTaxLabel.setText("Service Tax:");

        receiptServiceTax.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        receiptServiceTax.setForeground(new java.awt.Color(0, 153, 102));
        receiptServiceTax.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        receiptTourismTaxLabel.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        receiptTourismTaxLabel.setForeground(new java.awt.Color(51, 51, 255));
        receiptTourismTaxLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        receiptTourismTaxLabel.setText("Tourism Tax:");

        receiptTourismTax.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        receiptTourismTax.setForeground(new java.awt.Color(51, 51, 255));
        receiptTourismTax.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        receiptTotalPriceLabel.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        receiptTotalPriceLabel.setForeground(new java.awt.Color(204, 51, 0));
        receiptTotalPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        receiptTotalPriceLabel.setText("Total:");

        receiptTotalPrice.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        receiptTotalPrice.setForeground(new java.awt.Color(204, 51, 0));
        receiptTotalPrice.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        javax.swing.GroupLayout receiptPanelLayout = new javax.swing.GroupLayout(receiptPanel);
        receiptPanel.setLayout(receiptPanelLayout);
        receiptPanelLayout.setHorizontalGroup(
            receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receiptPanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, receiptPanelLayout.createSequentialGroup()
                            .addComponent(receiptTotalPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(receiptTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(receiptPanelLayout.createSequentialGroup()
                            .addComponent(receiptTourismTaxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(receiptTourismTax, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(receiptPanelLayout.createSequentialGroup()
                            .addComponent(receiptServiceTaxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(receiptServiceTax, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(receiptPanelLayout.createSequentialGroup()
                            .addComponent(receiptCustNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(receiptCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(receiptPanelLayout.createSequentialGroup()
                            .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(receiptStartDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(receiptDaysOfStayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(receiptPanelLayout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(receiptDaysOfStay, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, receiptPanelLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(receiptStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(receiptPanelLayout.createSequentialGroup()
                            .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(receiptBookingIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(receiptRoomIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(24, 24, 24)
                            .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(receiptRoomId, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(receiptBookingId, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        receiptPanelLayout.setVerticalGroup(
            receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receiptPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(receiptBookingId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receiptBookingIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(receiptRoomId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receiptRoomIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receiptStartDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receiptStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receiptDaysOfStay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receiptDaysOfStayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receiptCustNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receiptCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receiptServiceTaxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receiptServiceTax, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receiptTourismTaxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receiptTourismTax, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receiptTotalPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receiptTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Booking Form");
        setResizable(false);

        bookingFormLabel.setFont(new java.awt.Font("Pristina", 3, 36)); // NOI18N
        bookingFormLabel.setForeground(new java.awt.Color(0, 255, 204));
        bookingFormLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bookingFormLabel.setText("Booking Form");

        bookingIdLabel.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        bookingIdLabel.setForeground(new java.awt.Color(0, 0, 0));
        bookingIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bookingIdLabel.setText("Booking ID:");

        bookingIdField.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        bookingIdField.setEnabled(false);

        roomIdLabel.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        roomIdLabel.setForeground(new java.awt.Color(0, 0, 0));
        roomIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        roomIdLabel.setText("Room ID:");

        roomIdField.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        roomIdField.setEnabled(false);

        daysofStayLabel.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        daysofStayLabel.setForeground(new java.awt.Color(0, 0, 0));
        daysofStayLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        daysofStayLabel.setText("Days of Stay:");

        daysOfStayField.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        daysOfStayField.setEnabled(false);

        crtCustNameLabel.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        crtCustNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        crtCustNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        crtCustNameLabel.setText("Customer Name:");

        crtICNumLabel.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        crtICNumLabel.setForeground(new java.awt.Color(0, 0, 0));
        crtICNumLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        crtICNumLabel.setText("IC Number/Passport:");

        crtTelNoLabel.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        crtTelNoLabel.setForeground(new java.awt.Color(0, 0, 0));
        crtTelNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        crtTelNoLabel.setText("Telephone Number:");

        try {
            crtTelNoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        crtEmailLabel.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        crtEmailLabel.setForeground(new java.awt.Color(0, 0, 0));
        crtEmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        crtEmailLabel.setText("Email:");

        startDateLabel.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        startDateLabel.setForeground(new java.awt.Color(0, 0, 0));
        startDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        startDateLabel.setText("Start Date :");

        startDateField.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        startDateField.setEnabled(false);

        crtBookingBtn.setBackground(new java.awt.Color(0, 102, 255));
        crtBookingBtn.setFont(new java.awt.Font("Pristina", 0, 18)); // NOI18N
        crtBookingBtn.setForeground(new java.awt.Color(255, 255, 255));
        crtBookingBtn.setText("Create Booking!");
        crtBookingBtn.setMargin(new java.awt.Insets(5, 14, 2, 14));
        crtBookingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crtBookingBtnActionPerformed(evt);
            }
        });

        cancelBookingBtn.setBackground(new java.awt.Color(204, 51, 0));
        cancelBookingBtn.setFont(new java.awt.Font("Pristina", 0, 18)); // NOI18N
        cancelBookingBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBookingBtn.setText("Cancel");
        cancelBookingBtn.setMargin(new java.awt.Insets(5, 14, 2, 14));
        cancelBookingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBookingBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bookingFormLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(231, 231, 231))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(roomIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(startDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(daysofStayLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(crtEmailLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(crtTelNoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(crtICNumLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(crtCustNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bookingIdLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(startDateField, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(crtICNumField, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(roomIdField, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(bookingIdField, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(crtCustNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(crtEmailField, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(daysOfStayField, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(crtTelNoField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(crtBookingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(cancelBookingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookingFormLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookingIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookingIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomIdLabel)
                    .addComponent(roomIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startDateLabel)
                    .addComponent(startDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daysOfStayField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(daysofStayLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crtCustNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crtCustNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crtICNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crtICNumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crtTelNoLabel)
                    .addComponent(crtTelNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crtEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crtEmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crtBookingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBookingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBookingBtnActionPerformed
        dispose();
        new MainPage().setVisible(true);
    }//GEN-LAST:event_cancelBookingBtnActionPerformed

    private void crtBookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crtBookingBtnActionPerformed
        // initialize
        String customerName = crtCustNameField.getText();
        String ICNumber = crtICNumField.getText();
        String telephoneNumber = crtTelNoField.getText();
        String email = crtEmailField.getText();
        //validation
        if (customerName.isBlank()) {
            JOptionPane.showMessageDialog(this, "You cannot leave customer name field blank", "Warning Message", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (ICNumber.isBlank()) {
            JOptionPane.showMessageDialog(this, "You cannot leave IC Number field blank", "Warning Message", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (telephoneNumber.replace("-", "").isBlank()) {
            JOptionPane.showMessageDialog(this, "You cannot leave Telephone Number field blank", "Warning Message", JOptionPane.WARNING_MESSAGE);
            return;
        } else {

        }
        if (email.isBlank()) {
            JOptionPane.showMessageDialog(this, "You cannot leave Email field blank", "Warning Message", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            boolean isValidEmail = Pattern.matches(EMAIL_REGEX, email);
            if (!isValidEmail) {
                JOptionPane.showMessageDialog(this, "Please input a valid email", "Warning Message", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        //Calculate Price
        double basePrice = ROOM_PRICE_PER_NIGHT * daysOfStay;
        double serviceTax = basePrice * 0.1;
        double tourismTax = daysOfStay * 10;
        double price = basePrice + serviceTax + tourismTax;

        //Add booking
        try {
            BookingManager bm = new BookingManager();
            bm.addBooking(bookingId, roomId, customerName, ICNumber, telephoneNumber, email, startDate, endDate, price, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "There is an error occured when adding new booking\n" + e.getMessage(), "Error Message", JOptionPane.ERROR_MESSAGE);
        }
        //Show Receipt
        receiptBookingId.setText(bookingId);
        receiptRoomId.setText(roomId);
        receiptStartDate.setText(String.valueOf(startDate));
        receiptDaysOfStay.setText(String.valueOf(daysOfStay));
        receiptCustName.setText(customerName);
        receiptServiceTax.setText("RM" + String.format("%.2f", serviceTax));
        receiptTourismTax.setText("RM" + String.format("%.2f", tourismTax));
        receiptTotalPrice.setText("RM" + String.format("%.2f", price));
        JOptionPane.showMessageDialog(this, receiptPanel, "Receipt", JOptionPane.PLAIN_MESSAGE);
        //Dispose
        dispose();
        //new Main Page
        new MainPage().setVisible(true);
    }//GEN-LAST:event_crtBookingBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookingFormLabel;
    private javax.swing.JTextField bookingIdField;
    private javax.swing.JLabel bookingIdLabel;
    private javax.swing.JButton cancelBookingBtn;
    private javax.swing.JButton crtBookingBtn;
    private javax.swing.JTextField crtCustNameField;
    private javax.swing.JLabel crtCustNameLabel;
    private javax.swing.JTextField crtEmailField;
    private javax.swing.JLabel crtEmailLabel;
    private javax.swing.JTextField crtICNumField;
    private javax.swing.JLabel crtICNumLabel;
    private javax.swing.JFormattedTextField crtTelNoField;
    private javax.swing.JLabel crtTelNoLabel;
    private javax.swing.JTextField daysOfStayField;
    private javax.swing.JLabel daysofStayLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel receiptBookingId;
    private javax.swing.JLabel receiptBookingIdLabel;
    private javax.swing.JLabel receiptCustName;
    private javax.swing.JLabel receiptCustNameLabel;
    private javax.swing.JLabel receiptDaysOfStay;
    private javax.swing.JLabel receiptDaysOfStayLabel;
    private javax.swing.JPanel receiptPanel;
    private javax.swing.JLabel receiptRoomId;
    private javax.swing.JLabel receiptRoomIdLabel;
    private javax.swing.JLabel receiptServiceTax;
    private javax.swing.JLabel receiptServiceTaxLabel;
    private javax.swing.JLabel receiptStartDate;
    private javax.swing.JLabel receiptStartDateLabel;
    private javax.swing.JLabel receiptTotalPrice;
    private javax.swing.JLabel receiptTotalPriceLabel;
    private javax.swing.JLabel receiptTourismTax;
    private javax.swing.JLabel receiptTourismTaxLabel;
    private javax.swing.JTextField roomIdField;
    private javax.swing.JLabel roomIdLabel;
    private javax.swing.JTextField startDateField;
    private javax.swing.JLabel startDateLabel;
    // End of variables declaration//GEN-END:variables
}
